name: Docker Build and Pull

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  db_user: ${{ secrets.DB_USER }}
  db_password: ${{ secrets.DB_PASSWORD }}
  db_host: ${{ secrets.DB_HOST }}
  db_port: ${{ secrets.DB_PORT }}
  db_database: ${{ secrets.DB_DATABASE }}
  slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
  docker_hub_username: ${{ secrets.DOCKER_USERNAME }}
  docker_hub_pat: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub with PAT
        run: docker login -u ${{ env.docker_hub_username }} -p ${{ env.docker_hub_pat }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: phermaht/check_subs:latest

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          password: ${{ secrets.DEPLOY_SSH_PASSWORD }}
          port: 22
          script: |
            # Ваши команды развертывания
            docker stop check_subs || true
            docker rm check_subs || true
            docker pull phermaht/check_subs:latest
            docker run -d --name check_subs phermaht/check_subs:latest
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
