name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  user: ${{ secrets.USER }}
  password: ${{ secrets.PASSWORD }}
  host: ${{ secrets.HOST }}
  port: ${{ secrets.PORT }}
  database: ${{ secrets.DATABASE }}
  webhook: ${{ secrets.WEBHOOK }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag check_db_subs:$(date +%s)
